### ISSUE TITLE
Passing array of pages

### ISSUE THREAD

**Issue by Joebayld** [MihaelIsaev/wkhtmltopdf#2]
I'm noticing that you can't pass an array of [Page] to the WK.generate function. Seems that you use variadic arguments and that won't allow arrays as an input. Thoughts on changing this to accept an array. We could then add a convenience method to accept variadic arguments.

Joe

**Comment by MihaelIsaev** [comment]
@Joebayld thanks for reporting, hope now with 81290ac it works properly 👍

**Comment by Joebayld** [comment]
Works great - thanks!
