### ISSUE TITLE
Not work in Ubuntu Server

### ISSUE THREAD

**Issue by lucasromanomr** [MihaelIsaev/wkhtmltopdf#3]
the command to work in Ubuntu is: `xvfb-run wkhtmltopdf` if run only `wkhtmltopdf` return this message in console:

```
QXcbConnection: Could not connect to display :0
Aborted (core dumped)
```

**Comment by MihaelIsaev** [comment]
Hey @lucasromanomr 

On my Ubuntu 16.04 server on DigitalOcean it works from `/usr/bin/wkhtmltopdf` by default 🙂 

You can provide path to your `wkhtmltopdf` binary while initialization as binary place may be different
```swift
WK(pathToBinary: "/usr/bin/wkhtmltopdf")
```

Thanks for this issue, I'll add info about that into readme 👍
